"""New podcast values

Revision ID: d73d56d52cdc
Revises: 7558bb1393e1
Create Date: 2024-05-13 15:46:07.814579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73d56d52cdc'
down_revision = '7558bb1393e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('website', sa.String(length=1000), nullable=False))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('website')
        batch_op.drop_column('description')
        batch_op.drop_column('rss')

    # ### end Alembic commands ###
